### ISSUE TITLE
The quiz engine displays the incorrect feedback after navigating past a quiz item and then returning to it later

### ISSUE THREAD

**Issue by owlboy** [oel-mediateam/sbplus_v3#100] opened 2019-09-16 17:58 UTC
Hello, students are reporting issues with quiz items giving incorrect feedback.

Steps to reproduce:

1. Navigate to quiz item
2. Do not answer quiz item
3. Navigate to another quiz item
4. Return to the original unanswered quiz item
5. Answer the question correctly and see the feedback bar at the top is incorrect.

A screen recording demonstrating the issue:
https://youtu.be/C8OyQUQmpZo

Presentation used in the demonstration:
https://media.uwex.edu/content/apc/apc420/apc420_lesson2/

**Comment by Lin87** [comment] 2019-09-16 18:59
Should be fixed. Please confirm. The issue is caused by `this` pointer in JS.

**Closed** 2019-09-16 19:01 UTC
Labels: bug
